---

amq_streams_operator_packagemanifest: strimzi-kafka-operator
amq_streams_operator_subscription_name: strimzi-kafka-operator
amq_streams_operator_subscription_channel: stable
amq_streams_operator_subscription_automatic_installplan_approval: false
amq_streams_subscription_starting_csv: "strimzi-cluster-operator.v0.28.0"
amq_streams_operator_csv_prefix: strimzi-cluster-operator
amq_streams_operator_deployment: strimzi-cluster-operator
