{
 "title": "scm-business-KPIs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "SCM Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "am3x count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  count(id)\nFROM am3x" }
   ]
  },
  {
   "title": "ddas count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  count(id)\nFROM ddas" }
   ]
  },
  {
   "title": "detm count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  count(id)\nFROM detm" }
   ]
  },
  { "title": "CSV Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CSVs Rates (millis)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_redhat_himss_CSVPayloadProcessor_csvProcessingTimer_rate_per_second * 1000"
    }
   ]
  },
  {
   "title": "CSVs Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_redhat_himss_CSVPayloadProcessor_csvProcessed_total"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "JVM CPU Load Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent"
    }
   ]
  },
  {
   "title": "JVM Heap (GBs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes / 10^9"
    }
   ]
  },
  {
   "title": "JVM Uptime (Hrs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_jvm_uptime_seconds / 3600" }
   ]
  }
 ]
}