apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: generate-load-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: generate-load-job
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 1800
    backoffLimit: 6
    template:
      metadata:
        name: generate-load
      spec:
        containers:
        - name: scm-datagen
          image: quay.io/jkeam/scm-datagen@sha256:0474364412e2cb2e3c960150bf77b148efe028b771e25673b5346beb1c601e92
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: "RuntimeDefault"
          env:
          - name: SCM_UPLOAD_TIMES
            value: "${SCM_UPLOAD_TIMES}"
          - name: SCM_URL
            value: "${SCM_URL}/gzippedFiles"
        restartPolicy: OnFailure
parameters:
- name: SCM_URL
  description: "SCM Frontend URL to upload to"
- name: SCM_UPLOAD_TIMES
  description: "Number of times you want files generated and uploaded"
  value: "5"
